### ISSUE TITLE
package broken by github.com/olekukonko/tablewriter release v1.0 (used by github.com/jaytaylor/html2text)

### ISSUE THREAD

**Issue by jvegaseg** [jhillyerd/enmime#374]
This package is broken due packages html2text -> tablewriter:

```
../../../pkg/mod/github.com/jaytaylor/html2text@v0.0.0-20230321000545-74c2419ad056/html2text.go:41:35: undefined: tablewriter.Border
../../../pkg/mod/github.com/jaytaylor/html2text@v0.0.0-20230321000545-74c2419ad056/html2text.go:50:37: undefined: tablewriter.MAX_ROW_WIDTH
../../../pkg/mod/github.com/jaytaylor/html2text@v0.0.0-20230321000545-74c2419ad056/html2text.go:51:37: undefined: tablewriter.COLUMN
../../../pkg/mod/github.com/jaytaylor/html2text@v0.0.0-20230321000545-74c2419ad056/html2text.go:52:37: undefined: tablewriter.ROW
../../../pkg/mod/github.com/jaytaylor/html2text@v0.0.0-20230321000545-74c2419ad056/html2text.go:53:37: undefined: tablewriter.CENTER
../../../pkg/mod/github.com/jaytaylor/html2text@v0.0.0-20230321000545-74c2419ad056/html2text.go:54:37: undefined: tablewriter.ALIGN_DEFAULT
../../../pkg/mod/github.com/jaytaylor/html2text@v0.0.0-20230321000545-74c2419ad056/html2text.go:55:37: undefined: tablewriter.ALIGN_DEFAULT
../../../pkg/mod/github.com/jaytaylor/html2text@v0.0.0-20230321000545-74c2419ad056/html2text.go:56:37: undefined: tablewriter.ALIGN_DEFAULT
../../../pkg/mod/github.com/jaytaylor/html2text@v0.0.0-20230321000545-74c2419ad056/html2text.go:58:37: undefined: tablewriter.NEWLINE
../../../pkg/mod/github.com/jaytaylor/html2text@v0.0.0-20230321000545-74c2419ad056/html2text.go:62:37: undefined: tablewriter.Border
../../../pkg/mod/github.com/jaytaylor/html2text@v0.0.0-20230321000545-74c2419ad056/html2text.go:62:37: too many errors

```

In my case is no possible to use **replace** in go.mod because there are other packages using last version of tablewriter.

**Comment by jhillyerd** [comment]
Looks like https://github.com/Necoro/html2text is the most recent fork, but even it still uses the 0.x.x tablewriter.  Will probably have to make our own fork.

**Comment by lyda** [comment]
I'm seeing this issue as well. Happened when I moved tool management from [bingo](https://github.com/bwplotka/bingo) to [go tool](https://tip.golang.org/doc/modules/managing-dependencies#tools).

**Comment by jhillyerd** [comment]
Alright, I made a fork and switched to it.  Fix should be on `main` if anyone would like to test before the next release.

**Comment by nomaed** [comment]
Hey, any chance to add a version of this fix that doesn't require go1.24 somehow?

**Comment by jhillyerd** [comment]
@nomaed I can try, what go release are you running?

**Comment by jhillyerd** [comment]
Alright, https://github.com/jhillyerd/enmime/releases/tag/v2.2.0 should work with go 1.23
